/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anshv
 */
public class Beverages extends javax.swing.JFrame {

    /**
     * Creates new form Beverages
     */
    public Beverages() {
        initComponents();
        //Add Loop
        for(Products pp:MyClass.orderr)
        {
            if("LEMON ICED TEA       ".equals(pp.name))
            {
                this.jsp38.setValue(pp.qty);
            }
            if("MASALA BANTA         ".equals(pp.name))
            {
                this.jsp39.setValue(pp.qty);
            }
            if("VIRGIN MOJITO          ".equals(pp.name))
            {
                this.jsp40.setValue(pp.qty);
            }
            if("MANGO BANTA          ".equals(pp.name))
            {
                this.jsp41.setValue(pp.qty);
            }
            if("CHILLING COLDCOFFE".equals(pp.name))
            {
                this.jsp42.setValue(pp.qty);
            }
            if("STRAW. MILKSHAKE    ".equals(pp.name))
            {
                this.jsp43.setValue(pp.qty);
            }
            if("BUTTER. MILKSHAKE   ".equals(pp.name))
            {
                this.jsp44.setValue(pp.qty);
            }
            if("CHOC.ORE MILKSHAKE".equals(pp.name))
            {
                this.jsp45.setValue(pp.qty);
            }
            if("CARAMEL POP SHAKE ".equals(pp.name))
            {
                this.jsp46.setValue(pp.qty);
            }
            if("KIT KAT SHAKE            ".equals(pp.name))
            {
                this.jsp47.setValue(pp.qty);
            }
            if("HOT TEA                     ".equals(pp.name))
            {
                this.jsp48.setValue(pp.qty);
            }
            if("HOT COFFEE                ".equals(pp.name))
            {
                this.jsp49.setValue(pp.qty);
            }
            if("HAZELNUT COFFEE      ".equals(pp.name))
            {
                this.jsp50.setValue(pp.qty);
            }
            if("COFFEE MOCHA          ".equals(pp.name))
            {
                this.jsp51.setValue(pp.qty);
            }
            if("HOT CHOCOLATE       ".equals(pp.name))
            {
                this.jsp52.setValue(pp.qty);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Coolers = new java.awt.Label();
        Milkshake = new java.awt.Label();
        Ohhot = new java.awt.Label();
        Lemoniced = new javax.swing.JLabel();
        Masalabanta = new javax.swing.JLabel();
        VIrginmoj = new javax.swing.JLabel();
        Mangobanta = new javax.swing.JLabel();
        Chilling = new javax.swing.JLabel();
        Strawberry = new javax.swing.JLabel();
        Butterscotch = new javax.swing.JLabel();
        Chocooreo = new javax.swing.JLabel();
        Caramelpop = new javax.swing.JLabel();
        Kitkat = new javax.swing.JLabel();
        Hottea = new javax.swing.JLabel();
        Coffee = new javax.swing.JLabel();
        Hazelnuthot = new javax.swing.JLabel();
        Coffeemocha = new javax.swing.JLabel();
        Hotchoc = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        proceedtopay = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jsp38 = new javax.swing.JSpinner();
        jsp39 = new javax.swing.JSpinner();
        jsp40 = new javax.swing.JSpinner();
        jsp41 = new javax.swing.JSpinner();
        jsp42 = new javax.swing.JSpinner();
        jsp43 = new javax.swing.JSpinner();
        jsp44 = new javax.swing.JSpinner();
        jsp45 = new javax.swing.JSpinner();
        jsp46 = new javax.swing.JSpinner();
        jsp47 = new javax.swing.JSpinner();
        jsp48 = new javax.swing.JSpinner();
        jsp49 = new javax.swing.JSpinner();
        jsp50 = new javax.swing.JSpinner();
        jsp51 = new javax.swing.JSpinner();
        jsp52 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BEVERAGES");
        setLocation(new java.awt.Point(410, 20));
        setMaximumSize(new java.awt.Dimension(500, 640));
        setMinimumSize(new java.awt.Dimension(450, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        Coolers.setAlignment(java.awt.Label.CENTER);
        Coolers.setBackground(new java.awt.Color(102, 102, 102));
        Coolers.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Coolers.setForeground(new java.awt.Color(255, 255, 255));
        Coolers.setText("COOLERS");
        getContentPane().add(Coolers);
        Coolers.setBounds(0, 0, 450, 30);

        Milkshake.setAlignment(java.awt.Label.CENTER);
        Milkshake.setBackground(new java.awt.Color(102, 102, 102));
        Milkshake.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Milkshake.setForeground(new java.awt.Color(255, 255, 255));
        Milkshake.setText("MILKSHAKES");
        getContentPane().add(Milkshake);
        Milkshake.setBounds(0, 190, 450, 30);

        Ohhot.setAlignment(java.awt.Label.CENTER);
        Ohhot.setBackground(new java.awt.Color(102, 102, 102));
        Ohhot.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Ohhot.setForeground(new java.awt.Color(255, 255, 255));
        Ohhot.setText("OH ITS HOT!");
        getContentPane().add(Ohhot);
        Ohhot.setBounds(0, 380, 450, 30);

        Lemoniced.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lemoniced.setText("Lemon Iced Tea");
        getContentPane().add(Lemoniced);
        Lemoniced.setBounds(10, 35, 101, 25);

        Masalabanta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Masalabanta.setText("Masala Banta");
        getContentPane().add(Masalabanta);
        Masalabanta.setBounds(10, 65, 85, 25);

        VIrginmoj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        VIrginmoj.setText("Virgin Mojito");
        getContentPane().add(VIrginmoj);
        VIrginmoj.setBounds(10, 95, 87, 25);

        Mangobanta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mangobanta.setText("Mango Banta");
        getContentPane().add(Mangobanta);
        Mangobanta.setBounds(10, 125, 87, 25);

        Chilling.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Chilling.setText("Chilling Cold Coffee");
        getContentPane().add(Chilling);
        Chilling.setBounds(10, 155, 140, 25);

        Strawberry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Strawberry.setText("Strawberry Milkshake");
        getContentPane().add(Strawberry);
        Strawberry.setBounds(10, 225, 150, 25);

        Butterscotch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Butterscotch.setText("Butterscotch Milkshake");
        getContentPane().add(Butterscotch);
        Butterscotch.setBounds(10, 255, 160, 25);

        Chocooreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Chocooreo.setText("Choco Oreo Milkshake");
        getContentPane().add(Chocooreo);
        Chocooreo.setBounds(10, 285, 145, 25);

        Caramelpop.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Caramelpop.setText("Caramel Popcorn Shake");
        getContentPane().add(Caramelpop);
        Caramelpop.setBounds(10, 315, 154, 25);

        Kitkat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Kitkat.setText("Kit Kat Shake");
        getContentPane().add(Kitkat);
        Kitkat.setBounds(10, 345, 84, 25);

        Hottea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Hottea.setText("Hot Tea");
        getContentPane().add(Hottea);
        Hottea.setBounds(10, 415, 51, 25);

        Coffee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Coffee.setText("Hot Coffee");
        getContentPane().add(Coffee);
        Coffee.setBounds(10, 445, 100, 25);

        Hazelnuthot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Hazelnuthot.setText("Hazelnut Hot Coffee");
        getContentPane().add(Hazelnuthot);
        Hazelnuthot.setBounds(10, 475, 132, 25);

        Coffeemocha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Coffeemocha.setText("Coffee Mocha");
        getContentPane().add(Coffeemocha);
        Coffeemocha.setBounds(10, 505, 89, 25);

        Hotchoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Hotchoc.setText("Hot Chocolate");
        getContentPane().add(Hotchoc);
        Hotchoc.setBounds(10, 535, 92, 25);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 565, 450, 10);

        proceedtopay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        proceedtopay.setForeground(new java.awt.Color(255, 51, 51));
        proceedtopay.setText("PROCEED TO BILL");
        proceedtopay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedtopayActionPerformed(evt);
            }
        });
        getContentPane().add(proceedtopay);
        proceedtopay.setBounds(20, 570, 150, 30);

        menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu);
        menu.setBounds(190, 570, 110, 30);

        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(317, 570, 100, 30);

        jsp38.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp38.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp38);
        jsp38.setBounds(380, 35, 50, 25);

        jsp39.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp39.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp39);
        jsp39.setBounds(380, 65, 50, 25);

        jsp40.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp40.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp40);
        jsp40.setBounds(380, 95, 50, 25);

        jsp41.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp41.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp41);
        jsp41.setBounds(380, 125, 50, 25);

        jsp42.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp42.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp42);
        jsp42.setBounds(380, 155, 50, 25);

        jsp43.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp43.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp43);
        jsp43.setBounds(380, 225, 50, 25);

        jsp44.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp44.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp44);
        jsp44.setBounds(380, 255, 50, 25);

        jsp45.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp45.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp45);
        jsp45.setBounds(380, 285, 50, 25);

        jsp46.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp46.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp46.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp46);
        jsp46.setBounds(380, 315, 50, 25);

        jsp47.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp47.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp47.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp47);
        jsp47.setBounds(380, 345, 50, 25);

        jsp48.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp48.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp48.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp48);
        jsp48.setBounds(380, 415, 50, 25);

        jsp49.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp49.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp49.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp49);
        jsp49.setBounds(380, 445, 50, 25);

        jsp50.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp50.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp50);
        jsp50.setBounds(380, 475, 50, 25);

        jsp51.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp51.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp51);
        jsp51.setBounds(380, 505, 50, 25);

        jsp52.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp52.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp52.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp52);
        jsp52.setBounds(380, 535, 50, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("40/-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 35, 35, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("50/-");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 65, 35, 25);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("65/-");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 95, 35, 25);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("75/-");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(340, 125, 35, 25);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("90/-");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(340, 155, 35, 25);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("90/-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(340, 225, 35, 25);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("110/-");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(340, 255, 35, 25);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("125/-");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(340, 285, 35, 25);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("140/-");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(340, 315, 35, 25);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("155/-");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(340, 345, 35, 25);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("35/-");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(340, 415, 35, 25);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("55/-");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(340, 445, 35, 25);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("80/-");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(340, 475, 35, 25);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 51, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("110/-");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(340, 505, 35, 25);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("125/-");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(340, 535, 35, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kk.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 40, 110, 135);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 420, 110, 135);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kc.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 230, 110, 135);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBackground.jpg"))); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background);
        Background.setBounds(0, 0, 450, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        addItems();
        new Menu().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose(); 
        }
        void addItems()
        {
            int al=(Integer)jsp38.getValue();
            int am=(Integer)jsp39.getValue();
            int an=(Integer)jsp40.getValue();
            int ao=(Integer)jsp41.getValue();
            int ap=(Integer)jsp42.getValue();
            int aq=(Integer)jsp43.getValue();
            int ar=(Integer)jsp44.getValue();
            int as=(Integer)jsp45.getValue();
            int at=(Integer)jsp46.getValue();
            int au=(Integer)jsp47.getValue();
            int av=(Integer)jsp48.getValue();
            int aw=(Integer)jsp49.getValue();
            int ax=(Integer)jsp50.getValue();
            int ay=(Integer)jsp51.getValue();
            int az=(Integer)jsp52.getValue();
            if (al!=0)
                {
                    MyClass.orderr.add(new Products("LEMON ICED TEA       ",40,al));
                }
            if (am!=0)
                {
                    MyClass.orderr.add(new Products("MASALA BANTA         ",50,am));
                }
            if (an!=0)
                {
                    MyClass.orderr.add(new Products("VIRGIN MOJITO          ",65,al));
                }
            if (ao!=0)
                {   
                    MyClass.orderr.add(new Products("MANGO BANTA          ",75,ao));
                }
            if (ap!=0)
                {
                    MyClass.orderr.add(new Products("CHILLING COLDCOFFE",90,ap));
                }
            if (aq!=0)
                {
                    MyClass.orderr.add(new Products("STRAW. MILKSHAKE    ",90,aq));
                }
            if (ar!=0)
                {
                    MyClass.orderr.add(new Products("BUTTER. MILKSHAKE   ",110,ar));
                }
            if (as!=0)
                {
                    MyClass.orderr.add(new Products("CHOC.ORE MILKSHAKE",125,as));
                }
            if (at!=0)
                {
                    MyClass.orderr.add(new Products("CARAMEL POP SHAKE ",140,at));
                }
            if (au!=0)
                {
                    MyClass.orderr.add(new Products("KIT KAT SHAKE            ",155,au));
                }
            if (av!=0)
                {
                    MyClass.orderr.add(new Products("HOT TEA                     ",35,av));
                }       
            if (aw!=0)
                {
                    MyClass.orderr.add(new Products("HOT COFFEE                ",55,aw));
                }
            if (ax!=0)
                {
                    MyClass.orderr.add(new Products("HAZELNUT COFFEE      ",80,ax));
                }
            if (ay!=0)
                {
                    MyClass.orderr.add(new Products("COFFEE MOCHA          ",110,ay));
                }
            if (az!=0)
                {
                    MyClass.orderr.add(new Products("HOT CHOCOLATE       ",125,az));
                }// TODO add your handling code here: 
    }//GEN-LAST:event_exitActionPerformed

    private void proceedtopayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedtopayActionPerformed
    addItems();
    new Bill().setVisible(true);
    dispose();// TODO add your handling code here:
    }//GEN-LAST:event_proceedtopayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beverages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beverages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beverages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beverages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beverages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Butterscotch;
    private javax.swing.JLabel Caramelpop;
    private javax.swing.JLabel Chilling;
    private javax.swing.JLabel Chocooreo;
    private javax.swing.JLabel Coffee;
    private javax.swing.JLabel Coffeemocha;
    private java.awt.Label Coolers;
    private javax.swing.JLabel Hazelnuthot;
    private javax.swing.JLabel Hotchoc;
    private javax.swing.JLabel Hottea;
    private javax.swing.JLabel Kitkat;
    private javax.swing.JLabel Lemoniced;
    private javax.swing.JLabel Mangobanta;
    private javax.swing.JLabel Masalabanta;
    private java.awt.Label Milkshake;
    private java.awt.Label Ohhot;
    private javax.swing.JLabel Strawberry;
    private javax.swing.JLabel VIrginmoj;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jsp38;
    private javax.swing.JSpinner jsp39;
    private javax.swing.JSpinner jsp40;
    private javax.swing.JSpinner jsp41;
    private javax.swing.JSpinner jsp42;
    private javax.swing.JSpinner jsp43;
    private javax.swing.JSpinner jsp44;
    private javax.swing.JSpinner jsp45;
    private javax.swing.JSpinner jsp46;
    private javax.swing.JSpinner jsp47;
    private javax.swing.JSpinner jsp48;
    private javax.swing.JSpinner jsp49;
    private javax.swing.JSpinner jsp50;
    private javax.swing.JSpinner jsp51;
    private javax.swing.JSpinner jsp52;
    private javax.swing.JButton menu;
    private javax.swing.JButton proceedtopay;
    // End of variables declaration//GEN-END:variables
}
