/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anshv
 */
public class Meals extends javax.swing.JFrame {

    /**
     * Creates new form Meals
     */
    public Meals() {
        initComponents();
        //Add Loop
        for(Products pp:MyClass.orderr)
        {
            if("FRENCH FRIES             ".equals(pp.name))
            {
                this.jsp53.setValue(pp.qty);
            }
            if("TANGY TOMATO FRIES".equals(pp.name))
            {
                this.jsp54.setValue(pp.qty);
            }
            if("PERI-PERI FRIES           ".equals(pp.name))
            {
                this.jsp55.setValue(pp.qty);
            }
            if("TANDOORI FRIES         ".equals(pp.name))
            {
                this.jsp56.setValue(pp.qty);
            }
            if("ARABIAN FRIES            ".equals(pp.name))
            {
                this.jsp57.setValue(pp.qty);
            }
            if("CLASSIC MEAL             ".equals(pp.name))
            {
                this.jsp58.setValue(pp.qty);
            }
            if("HAPPY MEAL                ".equals(pp.name))
            {
                this.jsp59.setValue(pp.qty);
            }
            if("DOLLAR MEAL              ".equals(pp.name))
            {
                this.jsp60.setValue(pp.qty);
            }
            if("SUPER VALUE MEAL     ".equals(pp.name))
            {
                this.jsp61.setValue(pp.qty);
            }
            if("SPICY TONGUE MEAL   ".equals(pp.name))
            {
                this.jsp62.setValue(pp.qty);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Coolers = new java.awt.Label();
        Frenchfries = new javax.swing.JLabel();
        Tangytom = new javax.swing.JLabel();
        Periperi = new javax.swing.JLabel();
        Tandoori = new javax.swing.JLabel();
        Arabian = new javax.swing.JLabel();
        Milkshake = new java.awt.Label();
        Classicmeal = new javax.swing.JLabel();
        Des1 = new javax.swing.JLabel();
        Happymeal = new javax.swing.JLabel();
        Des2 = new javax.swing.JLabel();
        Dollarmeal = new javax.swing.JLabel();
        Des3 = new javax.swing.JLabel();
        Superval = new javax.swing.JLabel();
        Des4 = new javax.swing.JLabel();
        Superval1 = new javax.swing.JLabel();
        Des5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jsp53 = new javax.swing.JSpinner();
        jsp54 = new javax.swing.JSpinner();
        jsp55 = new javax.swing.JSpinner();
        jsp56 = new javax.swing.JSpinner();
        jsp57 = new javax.swing.JSpinner();
        jsp58 = new javax.swing.JSpinner();
        jsp59 = new javax.swing.JSpinner();
        jsp60 = new javax.swing.JSpinner();
        jsp61 = new javax.swing.JSpinner();
        jsp62 = new javax.swing.JSpinner();
        proceedtopay = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FRIES & MEALS");
        setLocation(new java.awt.Point(410, 50));
        setMaximumSize(new java.awt.Dimension(450, 535));
        setMinimumSize(new java.awt.Dimension(450, 535));
        setResizable(false);
        getContentPane().setLayout(null);

        Coolers.setAlignment(java.awt.Label.CENTER);
        Coolers.setBackground(new java.awt.Color(102, 102, 102));
        Coolers.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Coolers.setForeground(new java.awt.Color(255, 255, 255));
        Coolers.setText("FRIES");
        getContentPane().add(Coolers);
        Coolers.setBounds(0, 0, 450, 30);

        Frenchfries.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries.setText("French Fries");
        getContentPane().add(Frenchfries);
        Frenchfries.setBounds(10, 35, 90, 25);

        Tangytom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tangytom.setText("Tangy Tomato Fries");
        getContentPane().add(Tangytom);
        Tangytom.setBounds(10, 65, 130, 25);

        Periperi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Periperi.setText("Peri-peri Fries");
        getContentPane().add(Periperi);
        Periperi.setBounds(10, 95, 100, 25);

        Tandoori.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tandoori.setText("Tandoori Fries");
        getContentPane().add(Tandoori);
        Tandoori.setBounds(10, 125, 100, 25);

        Arabian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Arabian.setText("Arabian Fries");
        getContentPane().add(Arabian);
        Arabian.setBounds(10, 155, 100, 25);

        Milkshake.setAlignment(java.awt.Label.CENTER);
        Milkshake.setBackground(new java.awt.Color(102, 102, 102));
        Milkshake.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Milkshake.setForeground(new java.awt.Color(255, 255, 255));
        Milkshake.setText("MEALS");
        getContentPane().add(Milkshake);
        Milkshake.setBounds(0, 190, 450, 30);

        Classicmeal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Classicmeal.setText("Classic Meal");
        getContentPane().add(Classicmeal);
        Classicmeal.setBounds(10, 225, 150, 25);

        Des1.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des1.setText("(1 Couch Potato Burger, 1 French Fries, 500ml Pepsi)");
        Des1.setAlignmentY(0.0F);
        getContentPane().add(Des1);
        Des1.setBounds(10, 245, 250, 15);

        Happymeal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Happymeal.setText("Happy Meal");
        getContentPane().add(Happymeal);
        Happymeal.setBounds(10, 270, 150, 25);

        Des2.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des2.setText("(2 Punjabi Gabru Burger, 1 Peri-peri Fries, 500ml Pepsi)");
        Des2.setAlignmentY(0.0F);
        getContentPane().add(Des2);
        Des2.setBounds(10, 290, 260, 15);

        Dollarmeal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dollarmeal.setText("Dollar Meal");
        getContentPane().add(Dollarmeal);
        Dollarmeal.setBounds(10, 315, 150, 25);

        Des3.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des3.setText("(2 Veg. Makhani Burger, 1 Peri-peri Fries, 500ml Pepsi)");
        Des3.setAlignmentY(0.0F);
        getContentPane().add(Des3);
        Des3.setBounds(10, 335, 250, 15);

        Superval.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Superval.setText("Super Value Meal");
        getContentPane().add(Superval);
        Superval.setBounds(10, 360, 150, 25);

        Des4.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des4.setText("(2 Hot Chilli Burger, 2 Peri-peri Fries, 500ml Pepsi)");
        Des4.setAlignmentY(0.0F);
        getContentPane().add(Des4);
        Des4.setBounds(10, 380, 240, 15);

        Superval1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Superval1.setText("Spicy Tongue Meal");
        getContentPane().add(Superval1);
        Superval1.setBounds(10, 405, 150, 25);

        Des5.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des5.setText("(2 Veg Mighty Cheese Burger, 2 Arabian Fries, 500ml Pepsi)");
        Des5.setAlignmentY(0.0F);
        getContentPane().add(Des5);
        Des5.setBounds(10, 425, 280, 15);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 450, 450, 10);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("40/-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 35, 35, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("50/-");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 65, 35, 25);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("65/-");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 95, 35, 25);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("75/-");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(340, 125, 35, 25);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("80/-");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(340, 155, 35, 25);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("100/-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(340, 225, 35, 25);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("185/-");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(340, 270, 35, 25);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("210/-");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(340, 315, 35, 25);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("295/-");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(340, 360, 35, 25);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("350/-");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(340, 405, 35, 25);

        jsp53.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp53.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp53.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp53);
        jsp53.setBounds(380, 35, 50, 25);

        jsp54.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp54.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp54.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp54);
        jsp54.setBounds(380, 65, 50, 25);

        jsp55.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp55.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp55.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp55);
        jsp55.setBounds(380, 95, 50, 25);

        jsp56.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp56.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp56.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp56);
        jsp56.setBounds(380, 125, 50, 25);

        jsp57.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp57.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp57.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp57);
        jsp57.setBounds(380, 155, 50, 25);

        jsp58.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp58.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp58.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp58);
        jsp58.setBounds(380, 225, 50, 25);

        jsp59.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp59.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp59.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp59);
        jsp59.setBounds(380, 270, 50, 25);

        jsp60.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp60.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp60.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp60);
        jsp60.setBounds(380, 315, 50, 25);

        jsp61.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp61.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp61.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp61);
        jsp61.setBounds(380, 360, 50, 25);

        jsp62.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp62.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp62.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp62);
        jsp62.setBounds(380, 405, 50, 25);

        proceedtopay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        proceedtopay.setForeground(new java.awt.Color(255, 51, 51));
        proceedtopay.setText("PROCEED TO BILL");
        proceedtopay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedtopayActionPerformed(evt);
            }
        });
        getContentPane().add(proceedtopay);
        proceedtopay.setBounds(20, 460, 150, 30);

        menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu);
        menu.setBounds(187, 460, 105, 30);

        exit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit1.setText("EXIT");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        getContentPane().add(exit1);
        exit1.setBounds(317, 460, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pf.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 40, 130, 135);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBackground.jpg"))); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background);
        Background.setBounds(0, 0, 450, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        addItems();
        new Menu().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        dispose();
    }
    void addItems()
    {
       int ba=(Integer)jsp53.getValue();
        int bb=(Integer)jsp54.getValue();
        int bc=(Integer)jsp55.getValue();
        int bd=(Integer)jsp56.getValue();
        int be=(Integer)jsp57.getValue();
        int bf=(Integer)jsp58.getValue();
        int bg=(Integer)jsp59.getValue();
        int bh=(Integer)jsp60.getValue();
        int bi=(Integer)jsp61.getValue();
        int bj=(Integer)jsp62.getValue();
        if (ba!=0)
        {
            MyClass.orderr.add(new Products("FRENCH FRIES             ",40,ba));
        }
        if (bb!=0)
        {
            MyClass.orderr.add(new Products("TANGY TOMATO FRIES",50,bb));
        }
        if (bc!=0)
        {
            MyClass.orderr.add(new Products("PERI-PERI FRIES           ",65,bc));
        }
        if (bd!=0)
        {
            MyClass.orderr.add(new Products("TANDOORI FRIES         ",75,bd));
        }
        if (be!=0)
        {
            MyClass.orderr.add(new Products("ARABIAN FRIES            ",80,be));
        }
        if (bf!=0)
        {
            MyClass.orderr.add(new Products("CLASSIC MEAL             ",100,bf));
        }
        if (bg!=0)
        {
            MyClass.orderr.add(new Products("HAPPY MEAL                ",185,bg));
        }
        if (bh!=0)
        {
            MyClass.orderr.add(new Products("DOLLAR MEAL              ",210,bh));
        }
        if (bi!=0)
        {
            MyClass.orderr.add(new Products("SUPER VALUE MEAL     ",295,bi));
        }
        if (bj!=0)
        {
            MyClass.orderr.add(new Products("SPICY TONGUE MEAL   ",350,bj));
        } // TODO add your handling code here:
    }//GEN-LAST:event_exit1ActionPerformed

    private void proceedtopayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedtopayActionPerformed
    addItems();
    new Bill().setVisible(true);
    dispose();// TODO add your handling code here:
    }//GEN-LAST:event_proceedtopayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Arabian;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Classicmeal;
    private java.awt.Label Coolers;
    private javax.swing.JLabel Des1;
    private javax.swing.JLabel Des2;
    private javax.swing.JLabel Des3;
    private javax.swing.JLabel Des4;
    private javax.swing.JLabel Des5;
    private javax.swing.JLabel Dollarmeal;
    private javax.swing.JLabel Frenchfries;
    private javax.swing.JLabel Happymeal;
    private java.awt.Label Milkshake;
    private javax.swing.JLabel Periperi;
    private javax.swing.JLabel Superval;
    private javax.swing.JLabel Superval1;
    private javax.swing.JLabel Tandoori;
    private javax.swing.JLabel Tangytom;
    private javax.swing.JButton exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jsp53;
    private javax.swing.JSpinner jsp54;
    private javax.swing.JSpinner jsp55;
    private javax.swing.JSpinner jsp56;
    private javax.swing.JSpinner jsp57;
    private javax.swing.JSpinner jsp58;
    private javax.swing.JSpinner jsp59;
    private javax.swing.JSpinner jsp60;
    private javax.swing.JSpinner jsp61;
    private javax.swing.JSpinner jsp62;
    private javax.swing.JButton menu;
    private javax.swing.JButton proceedtopay;
    // End of variables declaration//GEN-END:variables
}
