import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ansh
 */
public class welcome extends javax.swing.JFrame {
    Connection con;
    java.sql.PreparedStatement stmt;
    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/db1?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
        }catch(Exception ee)
        {
            JOptionPane.showMessageDialog(this,"Start the Database Server");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        Hungryheads = new javax.swing.JLabel();
        welcome = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        newcust = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        managementlogin = new javax.swing.JButton();
        welcome1 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HUNGRYHEADS");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1000, 850));
        setMinimumSize(new java.awt.Dimension(740, 510));
        setResizable(false);
        getContentPane().setLayout(null);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(115, 180, 180, 35);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(115, 225, 180, 35);

        Hungryheads.setFont(new java.awt.Font("Tempus Sans ITC", 1, 45)); // NOI18N
        Hungryheads.setForeground(new java.awt.Color(255, 255, 255));
        Hungryheads.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hungryheads.setText("HUNGRYHEADS :)");
        getContentPane().add(Hungryheads);
        Hungryheads.setBounds(-5, 60, 410, 80);

        welcome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        welcome.setText("WELCOME");
        welcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcomeActionPerformed(evt);
            }
        });
        getContentPane().add(welcome);
        welcome.setBounds(20, 280, 170, 30);

        signup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signup.setText("SIGN-UP");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup);
        signup.setBounds(20, 315, 170, 30);

        newcust.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        newcust.setForeground(new java.awt.Color(255, 255, 255));
        newcust.setText("Sign-up, if you're a new customer.");
        getContentPane().add(newcust);
        newcust.setBounds(20, 340, 180, 16);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 183, 80, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone No.:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 225, 80, 30);

        managementlogin.setBackground(new java.awt.Color(102, 102, 102));
        managementlogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        managementlogin.setForeground(new java.awt.Color(255, 255, 255));
        managementlogin.setText("MANAGEMENT LOGIN");
        managementlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managementloginActionPerformed(evt);
            }
        });
        getContentPane().add(managementlogin);
        managementlogin.setBounds(20, 400, 170, 30);

        welcome1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        welcome1.setForeground(new java.awt.Color(255, 0, 51));
        welcome1.setText("CLEAR");
        welcome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcome1ActionPerformed(evt);
            }
        });
        getContentPane().add(welcome1);
        welcome1.setBounds(200, 280, 110, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/welcome.jpg"))); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background);
        Background.setBounds(0, -90, 1000, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    void addIn()
    {
        String abc=jTextField2.getText();
        String ddd=jTextField1.getText();
        MyClass.inf.add(new Info(abc,ddd));
    }
    private void welcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcomeActionPerformed
        addIn();
        String pn=jTextField1.getText();
        String nm=jTextField2.getText();
        try{
        Statement stt=con.createStatement();
        ResultSet rs=stt.executeQuery("Select * from credentials where phno='"+pn+"'");
        if(pn.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter number.");
        }
        else if(pn.length()<9)
        {
            JOptionPane.showMessageDialog(this, "Please enter valid number!");
        }
        else if(rs.next())
        {
            new Menu().setVisible(true);
        }
        else
            {
                JOptionPane.showMessageDialog(this,"New Customer Detected, Please SIGNUP!");
            }
    }catch(Exception ee){
        JOptionPane.showMessageDialog(this,"DB Error");
    }// TODO add your handling code here:
    }//GEN-LAST:event_welcomeActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
    new Register().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_signupActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        addIn();
        int a=evt.getKeyCode();
        if(a==10)
        {
        String pn=jTextField1.getText();
        try{
        Statement stt=con.createStatement();
        ResultSet rs=stt.executeQuery("Select * from credentials where phno='"+pn+"'");
        if(pn.equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter number.");
        }
        else if(rs.next())
        {
            new Menu().setVisible(true);
        }
        else
            {
                JOptionPane.showMessageDialog(this,"New Customer Detected, Please SIGNUP!");
            }
    }catch(Exception ee){
        JOptionPane.showMessageDialog(this,"DB Error");
    }  
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
    char c=evt.getKeyChar();
    String s=jTextField1.getText();
    if(c<48 || c>57 || s.length()>9)
    evt.consume(); // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
    char c=evt.getKeyChar();
    String s=jTextField2.getText();
    if(c<32 || c>122 || s.length()>40)
    evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyTyped

    private void managementloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managementloginActionPerformed
    new Managlogin().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_managementloginActionPerformed

    private void welcome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcome1ActionPerformed
    jTextField2.setText("");
    jTextField1.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_welcome1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Hungryheads;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    private javax.swing.JButton managementlogin;
    private javax.swing.JLabel newcust;
    private javax.swing.JButton signup;
    private javax.swing.JButton welcome;
    private javax.swing.JButton welcome1;
    // End of variables declaration//GEN-END:variables
}
