
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anshv
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hungryheads = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Version = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        Checkup = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ABOUT US");
        setLocation(new java.awt.Point(350, 90));
        setMaximumSize(new java.awt.Dimension(550, 450));
        setMinimumSize(new java.awt.Dimension(550, 450));
        setPreferredSize(new java.awt.Dimension(400, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        Hungryheads.setFont(new java.awt.Font("Tempus Sans ITC", 1, 45)); // NOI18N
        Hungryheads.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hungryheads.setText("HUNGRYHEADS :)");
        getContentPane().add(Hungryheads);
        Hungryheads.setBounds(0, 0, 550, 80);

        jScrollPane1.setVerifyInputWhenFocusTarget(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Hungryhead is a food chain which is popular for its remarkable\n taste in the food market. We have over 300 outlets in more \nthan 250 metropolitan cities such as Gurugram, New Delhi, \nAhemdabad, Ajmer, Meerut etc. and in hill stations such as \nMussorie, Manali, Nainital, Shimla etc. We ensure quality as \nthe ingredients we use are all organic and of best quality \nbecause your health is our priority. You'll find a great variety \nof items in our menu which are prepared by great chefs by \nkeeping every hygiene aspect in their mind. \nThankyou.");
        jTextArea1.setPreferredSize(new java.awt.Dimension(480, 224));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(23, 70, 490, 250);

        Version.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Version.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Version.setText("Version- 1.01                                     Developed by:- Ansh");
        getContentPane().add(Version);
        Version.setBounds(25, 330, 490, 30);

        menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu);
        menu.setBounds(25, 370, 150, 30);

        Checkup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Checkup.setText("CHECK FOR UPDATES");
        Checkup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckupActionPerformed(evt);
            }
        });
        getContentPane().add(Checkup);
        Checkup.setBounds(315, 370, 200, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBackground.jpg"))); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background);
        Background.setBounds(0, 0, 550, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        new Menu().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void CheckupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckupActionPerformed
    JOptionPane.showMessageDialog(this,"There are no updates available!");        // TODO add your handling code here:
    }//GEN-LAST:event_CheckupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Checkup;
    private javax.swing.JLabel Hungryheads;
    private javax.swing.JLabel Version;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton menu;
    // End of variables declaration//GEN-END:variables
}
