
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class Burger extends javax.swing.JFrame {

    /**
     * Creates new form Burger
     */
    public Burger() {
        initComponents();
        setSize(610,445);
        //Add Loop
        for(Products pp:MyClass.orderr)
        {
            if("COUCH POTATO         ".equals(pp.name))
            {
                this.jsp19.setValue(pp.qty);
            }
            if("PUNJABI GABRU         ".equals(pp.name))
            {
                this.jsp20.setValue(pp.qty);
            }
            if("VEG. MAKHNI BURGER".equals(pp.name))
            { 
                this.jsp21.setValue(pp.qty);
            }
            if("HOT CHILLI LAVA        ".equals(pp.name))
            {
                this.jsp22.setValue(pp.qty);
            }
            if("PEP JACK CHEESE        ".equals(pp.name))
            {
                this.jsp23.setValue(pp.qty);
            }
            if("VEG. MIGHTY CHEESE  ".equals(pp.name))
            {
                this.jsp24.setValue(pp.qty);
            }
            if("VEG. MEXICANBURGER".equals(pp.name))
            {
                this.jsp25.setValue(pp.qty);
            }
            if("ULTI. PANEER BURGER ".equals(pp.name))
            {
                this.jsp26.setValue(pp.qty);
            }
            if("ALOO TIKKI ROLL         ".equals(pp.name))
            {
                this.jsp27.setValue(pp.qty);
            }
            if("TANDOORI ALOO ROLL".equals(pp.name))
            {
                this.jsp28.setValue(pp.qty);
            }
            if("LACCHA PARATHAROLL".equals(pp.name))
            {
                this.jsp29.setValue(pp.qty);
            }
            if("SPRING ROLL(6 pcs.)     ".equals(pp.name))
            {
                this.jsp30.setValue(pp.qty);
            }
            if("NOODLE ROLL              ".equals(pp.name))
            {
                this.jsp31.setValue(pp.qty);
            }
            if("SWEET CORN ROLL       ".equals(pp.name))
            {
                this.jsp32.setValue(pp.qty);
            }
            if("VEG. MANCHUR. ROLL  ".equals(pp.name))
            {
                this.jsp33.setValue(pp.qty);
            }
            if("PANEER TIKKA ROLL     ".equals(pp.name))
            {
                this.jsp34.setValue(pp.qty);
            }
            if("CHILLI PANEER ROLL    ".equals(pp.name))
            {
                this.jsp35.setValue(pp.qty);
            }
            if("PIZZA ROLL                  ".equals(pp.name))
            {
                this.jsp36.setValue(pp.qty);
            }
            if("MALAAI CHAAP ROLL   ".equals(pp.name))
            {
                this.jsp37.setValue(pp.qty);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Burgers = new java.awt.Label();
        Wrapsrolls = new java.awt.Label();
        Couchpotato = new javax.swing.JLabel();
        Des1 = new javax.swing.JLabel();
        Punjabigabru = new javax.swing.JLabel();
        Des2 = new javax.swing.JLabel();
        Vegmakhani = new javax.swing.JLabel();
        Des3 = new javax.swing.JLabel();
        Hotchilli = new javax.swing.JLabel();
        Des4 = new javax.swing.JLabel();
        Pepperjack = new javax.swing.JLabel();
        Des5 = new javax.swing.JLabel();
        Vegmighty = new javax.swing.JLabel();
        Des6 = new javax.swing.JLabel();
        Vegmexican = new javax.swing.JLabel();
        Des7 = new javax.swing.JLabel();
        Ultimatepaneer = new javax.swing.JLabel();
        Des8 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jsp19 = new javax.swing.JSpinner();
        jsp20 = new javax.swing.JSpinner();
        jsp21 = new javax.swing.JSpinner();
        jsp22 = new javax.swing.JSpinner();
        jsp23 = new javax.swing.JSpinner();
        jsp24 = new javax.swing.JSpinner();
        jsp25 = new javax.swing.JSpinner();
        jsp26 = new javax.swing.JSpinner();
        jSeparator7 = new javax.swing.JSeparator();
        Alootikki = new javax.swing.JLabel();
        Tandoorialoo = new javax.swing.JLabel();
        Laccharoll = new javax.swing.JLabel();
        Springroll = new javax.swing.JLabel();
        Noodleroll = new javax.swing.JLabel();
        Sweetcorn = new javax.swing.JLabel();
        Vegmanchu = new javax.swing.JLabel();
        Paneertikka = new javax.swing.JLabel();
        Chillypaneer = new javax.swing.JLabel();
        Pizzaroll = new javax.swing.JLabel();
        Malaichaap = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jsp27 = new javax.swing.JSpinner();
        jsp28 = new javax.swing.JSpinner();
        jsp29 = new javax.swing.JSpinner();
        jsp30 = new javax.swing.JSpinner();
        jsp31 = new javax.swing.JSpinner();
        jsp32 = new javax.swing.JSpinner();
        jsp33 = new javax.swing.JSpinner();
        jsp34 = new javax.swing.JSpinner();
        jsp35 = new javax.swing.JSpinner();
        jsp36 = new javax.swing.JSpinner();
        jsp37 = new javax.swing.JSpinner();
        proceedtopay = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BURGERS & ROLLS\n");
        setLocation(new java.awt.Point(300, 100));
        setResizable(false);
        getContentPane().setLayout(null);

        Burgers.setAlignment(java.awt.Label.CENTER);
        Burgers.setBackground(new java.awt.Color(102, 102, 102));
        Burgers.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Burgers.setForeground(new java.awt.Color(255, 255, 255));
        Burgers.setText("BURGERS");
        getContentPane().add(Burgers);
        Burgers.setBounds(0, 0, 290, 30);

        Wrapsrolls.setAlignment(java.awt.Label.CENTER);
        Wrapsrolls.setBackground(new java.awt.Color(102, 102, 102));
        Wrapsrolls.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Wrapsrolls.setForeground(new java.awt.Color(255, 255, 255));
        Wrapsrolls.setText("ROLLS");
        getContentPane().add(Wrapsrolls);
        Wrapsrolls.setBounds(308, 0, 290, 30);

        Couchpotato.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Couchpotato.setText("Couch Potato");
        getContentPane().add(Couchpotato);
        Couchpotato.setBounds(5, 35, 124, 25);

        Des1.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des1.setText("(Aloo Tikki, Chrispy Patty, Onion)");
        Des1.setAlignmentY(0.0F);
        getContentPane().add(Des1);
        Des1.setBounds(5, 55, 145, 12);

        Punjabigabru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Punjabigabru.setText("Punjabi Gabru");
        getContentPane().add(Punjabigabru);
        Punjabigabru.setBounds(5, 75, 124, 25);

        Des2.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des2.setText("(7 Spice Patty, Onion, Tomato, Tangy Sauce)");
        Des2.setAlignmentY(0.0F);
        getContentPane().add(Des2);
        Des2.setBounds(5, 95, 190, 12);

        Vegmakhani.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Vegmakhani.setText("Veg Makhni Burger");
        getContentPane().add(Vegmakhani);
        Vegmakhani.setBounds(5, 115, 140, 25);

        Des3.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des3.setText("(Toasted Buns, Makhani Sauce, Mayo., Onion) ");
        Des3.setAlignmentY(0.0F);
        getContentPane().add(Des3);
        Des3.setBounds(5, 135, 195, 12);

        Hotchilli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Hotchilli.setText("Hot Chilli Lava");
        getContentPane().add(Hotchilli);
        Hotchilli.setBounds(5, 155, 124, 25);

        Des4.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des4.setText("(Chrispy Buns, Spicy Veggie Patty, Chilli Sauce)");
        Des4.setAlignmentY(0.0F);
        getContentPane().add(Des4);
        Des4.setBounds(5, 175, 212, 12);

        Pepperjack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pepperjack.setText("Pepper Jack Cheese");
        getContentPane().add(Pepperjack);
        Pepperjack.setBounds(5, 195, 130, 25);

        Des5.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des5.setText("(Pepper Patty, Pepper Sauce, Veggies, Cheese) ");
        Des5.setAlignmentY(0.0F);
        getContentPane().add(Des5);
        Des5.setBounds(5, 215, 200, 12);

        Vegmighty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Vegmighty.setText("Veg Mighty Cheese");
        getContentPane().add(Vegmighty);
        Vegmighty.setBounds(5, 235, 130, 25);

        Des6.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des6.setText("(Tangy Patty, Salsa Sauce, Nachos, Veggies)");
        Des6.setAlignmentY(0.0F);
        getContentPane().add(Des6);
        Des6.setBounds(5, 295, 190, 12);

        Vegmexican.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Vegmexican.setText("Veg Mexican Burger");
        getContentPane().add(Vegmexican);
        Vegmexican.setBounds(5, 275, 140, 25);

        Des7.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des7.setText("(Cheese Burst Patty, Spicy Sauce, Mayo., Veggies)");
        Des7.setAlignmentY(0.0F);
        getContentPane().add(Des7);
        Des7.setBounds(5, 255, 210, 12);

        Ultimatepaneer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ultimatepaneer.setText("Ultimate Paneer Burger");
        getContentPane().add(Ultimatepaneer);
        Ultimatepaneer.setBounds(5, 315, 160, 25);

        Des8.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des8.setText("(Crunchy Paneer Patty, Smoked Sauce, Veggies)");
        Des8.setAlignmentY(0.0F);
        getContentPane().add(Des8);
        Des8.setBounds(5, 335, 210, 12);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("40/-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 35, 35, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("55/-");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 75, 35, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("70/-");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 115, 35, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("75/-");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(200, 155, 35, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("75/-");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(200, 195, 35, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("90/-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(200, 235, 35, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("105/-");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(200, 275, 35, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("120/-");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(200, 315, 35, 30);

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(0, 364, 684, 3);

        jsp19.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp19.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp19);
        jsp19.setBounds(240, 35, 50, 30);

        jsp20.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp20.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp20);
        jsp20.setBounds(240, 75, 50, 30);

        jsp21.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp21.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp21);
        jsp21.setBounds(240, 115, 50, 30);

        jsp22.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp22.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp22);
        jsp22.setBounds(240, 155, 50, 30);

        jsp23.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp23.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp23);
        jsp23.setBounds(240, 195, 50, 30);

        jsp24.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp24.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp24);
        jsp24.setBounds(240, 235, 50, 30);

        jsp25.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp25.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp25);
        jsp25.setBounds(240, 275, 50, 30);

        jsp26.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp26.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp26);
        jsp26.setBounds(240, 315, 50, 30);

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(298, 0, 10, 364);

        Alootikki.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Alootikki.setText("Aloo Tikki Roll");
        getContentPane().add(Alootikki);
        Alootikki.setBounds(310, 35, 140, 25);

        Tandoorialoo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tandoorialoo.setText("Tandoori Aloo Roll");
        getContentPane().add(Tandoorialoo);
        Tandoorialoo.setBounds(310, 65, 140, 25);

        Laccharoll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Laccharoll.setText("Laccha Paratha Roll");
        getContentPane().add(Laccharoll);
        Laccharoll.setBounds(310, 95, 140, 25);

        Springroll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Springroll.setText("Spring Roll (6 pcs.)");
        getContentPane().add(Springroll);
        Springroll.setBounds(310, 125, 140, 25);

        Noodleroll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Noodleroll.setText("Noodle Roll");
        getContentPane().add(Noodleroll);
        Noodleroll.setBounds(310, 155, 140, 25);

        Sweetcorn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Sweetcorn.setText("Sweet Corn Roll");
        getContentPane().add(Sweetcorn);
        Sweetcorn.setBounds(310, 185, 150, 25);

        Vegmanchu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Vegmanchu.setText("Veg. Manchurian Roll");
        getContentPane().add(Vegmanchu);
        Vegmanchu.setBounds(310, 215, 150, 25);

        Paneertikka.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Paneertikka.setText("Paneer Tikka Roll");
        getContentPane().add(Paneertikka);
        Paneertikka.setBounds(310, 245, 140, 25);

        Chillypaneer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Chillypaneer.setText("Chilli Paneer Roll");
        getContentPane().add(Chillypaneer);
        Chillypaneer.setBounds(310, 275, 140, 25);

        Pizzaroll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pizzaroll.setText("Pizza Roll");
        getContentPane().add(Pizzaroll);
        Pizzaroll.setBounds(310, 305, 140, 25);

        Malaichaap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Malaichaap.setText("Malaai Chaap Roll");
        getContentPane().add(Malaichaap);
        Malaichaap.setBounds(310, 335, 150, 25);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("35/-");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(480, 35, 35, 25);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("45/-");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(480, 65, 35, 25);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("55/-");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(480, 95, 35, 25);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("65/-");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(480, 125, 35, 25);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("75/-");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(480, 155, 35, 25);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 51, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("85/-");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(480, 185, 35, 25);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("95/-");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(480, 215, 35, 25);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 51, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("105/-");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(480, 245, 35, 25);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("115/-");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(480, 275, 35, 25);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("125/-");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(480, 305, 35, 25);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 51, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("135/-");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(480, 335, 35, 25);

        jsp27.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp27.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp27);
        jsp27.setBounds(530, 35, 50, 25);

        jsp28.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp28.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp28);
        jsp28.setBounds(530, 65, 50, 25);

        jsp29.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp29.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp29);
        jsp29.setBounds(530, 95, 50, 25);

        jsp30.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp30.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp30);
        jsp30.setBounds(530, 125, 50, 25);

        jsp31.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp31.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp31);
        jsp31.setBounds(530, 155, 50, 25);

        jsp32.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp32.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp32);
        jsp32.setBounds(530, 185, 50, 25);

        jsp33.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp33.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp33);
        jsp33.setBounds(530, 215, 50, 25);

        jsp34.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp34.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp34);
        jsp34.setBounds(530, 245, 50, 25);

        jsp35.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp35.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp35);
        jsp35.setBounds(530, 275, 50, 25);

        jsp36.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp36.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp36);
        jsp36.setBounds(530, 305, 50, 25);

        jsp37.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp37.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp37);
        jsp37.setBounds(530, 335, 50, 25);

        proceedtopay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        proceedtopay.setForeground(new java.awt.Color(255, 51, 51));
        proceedtopay.setText("PROCEED TO BILL");
        proceedtopay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedtopayActionPerformed(evt);
            }
        });
        getContentPane().add(proceedtopay);
        proceedtopay.setBounds(220, 370, 150, 30);

        menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu);
        menu.setBounds(377, 370, 110, 30);

        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(493, 370, 100, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBackground.jpg"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(600, 480));
        Background.setMinimumSize(new java.awt.Dimension(600, 480));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 600, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        addItems();
        new Menu().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed
    void addItems()
    {
    int s=(Integer)jsp19.getValue();
    int t=(Integer)jsp20.getValue();
    int u=(Integer)jsp21.getValue();
    int v=(Integer)jsp22.getValue();
    int w=(Integer)jsp23.getValue();
    int x=(Integer)jsp24.getValue();
    int y=(Integer)jsp25.getValue();
    int z=(Integer)jsp26.getValue();
    int aa=(Integer)jsp27.getValue();
    int ab=(Integer)jsp28.getValue();
    int ac=(Integer)jsp29.getValue();
    int ad=(Integer)jsp30.getValue();
    int ae=(Integer)jsp31.getValue();
    int af=(Integer)jsp32.getValue();
    int ag=(Integer)jsp33.getValue();
    int ah=(Integer)jsp34.getValue();
    int ai=(Integer)jsp35.getValue();
    int aj=(Integer)jsp36.getValue();
    int ak=(Integer)jsp37.getValue();
    if (s!=0)
        {
            MyClass.orderr.add(new Products("COUCH POTATO         ",40,s)); 
        }
    if (t!=0)
        {
            MyClass.orderr.add(new Products("PUNJABI GABRU         ",55,t));  
        }
    if (u!=0)
        {
            MyClass.orderr.add(new Products("VEG. MAKHNI BURGER",70,u));
        }
     if (v!=0)
        {
            MyClass.orderr.add(new Products("HOT CHILLI LAVA        ",75,v));
        }
     if (w!=0)
        {
            MyClass.orderr.add(new Products("PEP JACK CHEESE        ",75,w));
        }
     if (x!=0)
        {
            MyClass.orderr.add(new Products("VEG. MIGHTY CHEESE  ",90,x));
        }
     if (y!=0)
        {
            MyClass.orderr.add(new Products("VEG. MEXICANBURGER",105,y));
        }
     if (z!=0)
        {
            MyClass.orderr.add(new Products("ULTI. PANEER BURGER ",120,z));
        }
     if (aa!=0)
        {
            MyClass.orderr.add(new Products("ALOO TIKKI ROLL         ",35,aa));
        }
     if (ab!=0)
        {
            MyClass.orderr.add(new Products("TANDOORI ALOO ROLL",45,ab));
        }
     if (ac!=0)
        {
            MyClass.orderr.add(new Products("LACCHA PARATHAROLL",55,ac));
        }
     if (ad!=0)
        {
            MyClass.orderr.add(new Products("SPRING ROLL(6 pcs.)     ",65,ad));
        }
     if (ae!=0)
        {
            MyClass.orderr.add(new Products("NOODLE ROLL              ",75,ae));
        }
     if (af!=0)
        {
            MyClass.orderr.add(new Products("SWEET CORN ROLL       ",85,af));
        }
     if (ag!=0)
        {
            MyClass.orderr.add(new Products("VEG. MANCHUR. ROLL  ",95,ag));
        }
     if (ah!=0)
        {
            MyClass.orderr.add(new Products("PANEER TIKKA ROLL     ",105,ah));
        }
     if (ai!=0)
        {
            MyClass.orderr.add(new Products("CHILLI PANEER ROLL    ",115,ai));
        }
     if (aj!=0)
        {
            MyClass.orderr.add(new Products("PIZZA ROLL                  ",125,aj));
        }
     if (ak!=0)
        {
            MyClass.orderr.add(new Products("MALAAI CHAAP ROLL   ",135,ak));
        }
    }
    private void proceedtopayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedtopayActionPerformed
        addItems();
        new Bill().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_proceedtopayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Burger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Burger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Burger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Burger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Burger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alootikki;
    private javax.swing.JLabel Background;
    private java.awt.Label Burgers;
    private javax.swing.JLabel Chillypaneer;
    private javax.swing.JLabel Couchpotato;
    private javax.swing.JLabel Des1;
    private javax.swing.JLabel Des2;
    private javax.swing.JLabel Des3;
    private javax.swing.JLabel Des4;
    private javax.swing.JLabel Des5;
    private javax.swing.JLabel Des6;
    private javax.swing.JLabel Des7;
    private javax.swing.JLabel Des8;
    private javax.swing.JLabel Hotchilli;
    private javax.swing.JLabel Laccharoll;
    private javax.swing.JLabel Malaichaap;
    private javax.swing.JLabel Noodleroll;
    private javax.swing.JLabel Paneertikka;
    private javax.swing.JLabel Pepperjack;
    private javax.swing.JLabel Pizzaroll;
    private javax.swing.JLabel Punjabigabru;
    private javax.swing.JLabel Springroll;
    private javax.swing.JLabel Sweetcorn;
    private javax.swing.JLabel Tandoorialoo;
    private javax.swing.JLabel Ultimatepaneer;
    private javax.swing.JLabel Vegmakhani;
    private javax.swing.JLabel Vegmanchu;
    private javax.swing.JLabel Vegmexican;
    private javax.swing.JLabel Vegmighty;
    private java.awt.Label Wrapsrolls;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSpinner jsp19;
    private javax.swing.JSpinner jsp20;
    private javax.swing.JSpinner jsp21;
    private javax.swing.JSpinner jsp22;
    private javax.swing.JSpinner jsp23;
    private javax.swing.JSpinner jsp24;
    private javax.swing.JSpinner jsp25;
    private javax.swing.JSpinner jsp26;
    private javax.swing.JSpinner jsp27;
    private javax.swing.JSpinner jsp28;
    private javax.swing.JSpinner jsp29;
    private javax.swing.JSpinner jsp30;
    private javax.swing.JSpinner jsp31;
    private javax.swing.JSpinner jsp32;
    private javax.swing.JSpinner jsp33;
    private javax.swing.JSpinner jsp34;
    private javax.swing.JSpinner jsp35;
    private javax.swing.JSpinner jsp36;
    private javax.swing.JSpinner jsp37;
    private javax.swing.JButton menu;
    private javax.swing.JButton proceedtopay;
    // End of variables declaration//GEN-END:variables
}
