/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anshv
 */
public class Deserts extends javax.swing.JFrame {

    /**
     * Creates new form Deserts
     */
    public Deserts() {
        initComponents();
        //Add Loop
        for(Products pp:MyClass.orderr)
        {
            if("VANILLA SOFT SERVE ".equals(pp.name))
            {
                this.jsp63.setValue(pp.qty);
            }
            if("BUTTER. SOFT SERVE  ".equals(pp.name))
            {
                this.jsp64.setValue(pp.qty);
            }
            if("CHOC DIPSOFT SERVE".equals(pp.name))
            {
                this.jsp65.setValue(pp.qty);
            }
            if("STRAWBERRY SCOOP ".equals(pp.name))
            {
                this.jsp66.setValue(pp.qty);
            }
            if("RAINBOW SUNDAE    ".equals(pp.name))
            {
                this.jsp67.setValue(pp.qty);
            }
            if("KIT-KAT MCFLURRY    ".equals(pp.name))
            {
                this.jsp68.setValue(pp.qty);
            }
            if("DRY MUFFIN  CAKE    ".equals(pp.name))
            {
                this.jsp69.setValue(pp.qty);
            }
            if("CHOCO LAVA  CAKE   ".equals(pp.name))
            {
                this.jsp70.setValue(pp.qty);
            }
            if("CHOCOLATEBROWNIE".equals(pp.name))
            {
                this.jsp71.setValue(pp.qty);
            }
            if("RED VELVET PASTRY   ".equals(pp.name))
            {
                this.jsp72.setValue(pp.qty);
            }
            if("FRUIT CHEESE PASTRY".equals(pp.name))
            {
                this.jsp73.setValue(pp.qty);
            }
            if("GULAB-JAMUN(1pc.)  ".equals(pp.name))
            {
                this.jsp74.setValue(pp.qty);
            }
            if("MOONG DAL HALWA".equals(pp.name))
            {
                this.jsp75.setValue(pp.qty);
            }
            if("GAJAR HALWA            ".equals(pp.name))
            {
                this.jsp76.setValue(pp.qty);
            }
            if("RASMALAAI (1pc.)       ".equals(pp.name))
            {
                this.jsp77.setValue(pp.qty);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Coolers = new java.awt.Label();
        Frenchfries = new javax.swing.JLabel();
        Frenchfries1 = new javax.swing.JLabel();
        Frenchfries2 = new javax.swing.JLabel();
        Frenchfries3 = new javax.swing.JLabel();
        Frenchfries4 = new javax.swing.JLabel();
        Frenchfries5 = new javax.swing.JLabel();
        Frenchfries6 = new javax.swing.JLabel();
        Milkshake = new java.awt.Label();
        Frenchfries7 = new javax.swing.JLabel();
        Frenchfries8 = new javax.swing.JLabel();
        Frenchfries9 = new javax.swing.JLabel();
        Frenchfries10 = new javax.swing.JLabel();
        Frenchfries11 = new javax.swing.JLabel();
        Milkshake1 = new java.awt.Label();
        Frenchfries12 = new javax.swing.JLabel();
        Frenchfries13 = new javax.swing.JLabel();
        Frenchfries14 = new javax.swing.JLabel();
        Frenchfries15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        proceedtopay = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jsp63 = new javax.swing.JSpinner();
        jsp64 = new javax.swing.JSpinner();
        jsp65 = new javax.swing.JSpinner();
        jsp66 = new javax.swing.JSpinner();
        jsp67 = new javax.swing.JSpinner();
        jsp68 = new javax.swing.JSpinner();
        jsp69 = new javax.swing.JSpinner();
        jsp70 = new javax.swing.JSpinner();
        jsp71 = new javax.swing.JSpinner();
        jsp72 = new javax.swing.JSpinner();
        jsp73 = new javax.swing.JSpinner();
        jsp74 = new javax.swing.JSpinner();
        jsp75 = new javax.swing.JSpinner();
        jsp76 = new javax.swing.JSpinner();
        jsp77 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DESERTS");
        setLocation(new java.awt.Point(410, 20));
        setMaximumSize(new java.awt.Dimension(450, 640));
        setMinimumSize(new java.awt.Dimension(450, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        Coolers.setAlignment(java.awt.Label.CENTER);
        Coolers.setBackground(new java.awt.Color(102, 102, 102));
        Coolers.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Coolers.setForeground(new java.awt.Color(255, 255, 255));
        Coolers.setText("ICE-CREAMS");
        getContentPane().add(Coolers);
        Coolers.setBounds(0, 0, 450, 30);

        Frenchfries.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries.setText("Vanilla Soft Serve");
        getContentPane().add(Frenchfries);
        Frenchfries.setBounds(10, 35, 120, 25);

        Frenchfries1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries1.setText("Butterscotch Soft Serve");
        getContentPane().add(Frenchfries1);
        Frenchfries1.setBounds(10, 65, 160, 25);

        Frenchfries2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries2.setText("Chocolate Dip Soft Serve");
        getContentPane().add(Frenchfries2);
        Frenchfries2.setBounds(10, 95, 170, 25);

        Frenchfries3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries3.setText("Strawberry Scoop");
        getContentPane().add(Frenchfries3);
        Frenchfries3.setBounds(10, 125, 120, 25);

        Frenchfries4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries4.setText("Strawberry Scoop");
        getContentPane().add(Frenchfries4);
        Frenchfries4.setBounds(10, 125, 120, 25);

        Frenchfries5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries5.setText("Rainbow Sundae");
        getContentPane().add(Frenchfries5);
        Frenchfries5.setBounds(10, 155, 120, 25);

        Frenchfries6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries6.setText("Kit-Kat McFlurry");
        getContentPane().add(Frenchfries6);
        Frenchfries6.setBounds(10, 185, 120, 25);

        Milkshake.setAlignment(java.awt.Label.CENTER);
        Milkshake.setBackground(new java.awt.Color(102, 102, 102));
        Milkshake.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Milkshake.setForeground(new java.awt.Color(255, 255, 255));
        Milkshake.setText("CAKES");
        getContentPane().add(Milkshake);
        Milkshake.setBounds(0, 220, 450, 30);

        Frenchfries7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries7.setText("Dry Muffin Cake");
        getContentPane().add(Frenchfries7);
        Frenchfries7.setBounds(10, 255, 170, 25);

        Frenchfries8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries8.setText("Choco Lava Cake");
        getContentPane().add(Frenchfries8);
        Frenchfries8.setBounds(10, 285, 170, 25);

        Frenchfries9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries9.setText("Fruit Cheese Pastry");
        getContentPane().add(Frenchfries9);
        Frenchfries9.setBounds(10, 375, 170, 25);

        Frenchfries10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries10.setText("Red Velvet Pastry");
        getContentPane().add(Frenchfries10);
        Frenchfries10.setBounds(10, 345, 170, 25);

        Frenchfries11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries11.setText("Chocolate Brownie");
        getContentPane().add(Frenchfries11);
        Frenchfries11.setBounds(10, 315, 170, 25);

        Milkshake1.setAlignment(java.awt.Label.CENTER);
        Milkshake1.setBackground(new java.awt.Color(102, 102, 102));
        Milkshake1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Milkshake1.setForeground(new java.awt.Color(255, 255, 255));
        Milkshake1.setText("DESERTS");
        getContentPane().add(Milkshake1);
        Milkshake1.setBounds(0, 410, 450, 30);

        Frenchfries12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries12.setText("Gulab-jamun (1 pc.)");
        getContentPane().add(Frenchfries12);
        Frenchfries12.setBounds(10, 445, 170, 25);

        Frenchfries13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries13.setText("Moong Dal Halwa");
        getContentPane().add(Frenchfries13);
        Frenchfries13.setBounds(10, 475, 170, 25);

        Frenchfries14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries14.setText("Gajar Halwa");
        getContentPane().add(Frenchfries14);
        Frenchfries14.setBounds(10, 505, 170, 25);

        Frenchfries15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Frenchfries15.setText("Rasmalaai (1 pc.)");
        getContentPane().add(Frenchfries15);
        Frenchfries15.setBounds(10, 535, 170, 25);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 565, 450, 10);

        proceedtopay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        proceedtopay.setForeground(new java.awt.Color(255, 51, 51));
        proceedtopay.setText("PROCEED TO BILL");
        proceedtopay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedtopayActionPerformed(evt);
            }
        });
        getContentPane().add(proceedtopay);
        proceedtopay.setBounds(20, 570, 150, 30);

        menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu);
        menu.setBounds(192, 570, 105, 30);

        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(317, 570, 100, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("15/-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 35, 35, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("20/-");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 65, 35, 25);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("25/-");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 95, 35, 25);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("40/-");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(340, 125, 35, 25);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("55/-");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(340, 155, 35, 25);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("65/-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(340, 185, 35, 25);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("30/-");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(340, 255, 35, 25);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("45/-");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(340, 285, 35, 25);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("65/-");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(340, 315, 35, 25);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("70/-");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(340, 345, 35, 25);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("80/-");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(340, 375, 35, 25);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("15/-");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(340, 445, 35, 25);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("40/-");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(340, 475, 35, 25);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 51, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("45/-");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(340, 505, 35, 25);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("20/-");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(340, 535, 35, 25);

        jsp63.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp63.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp63.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp63);
        jsp63.setBounds(380, 35, 50, 25);

        jsp64.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp64.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp64.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp64);
        jsp64.setBounds(380, 65, 50, 25);

        jsp65.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp65.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp65.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp65);
        jsp65.setBounds(380, 95, 50, 25);

        jsp66.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp66.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp66.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp66);
        jsp66.setBounds(380, 125, 50, 25);

        jsp67.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp67.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp67.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp67);
        jsp67.setBounds(380, 155, 50, 25);

        jsp68.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp68.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp68.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp68);
        jsp68.setBounds(380, 185, 50, 25);

        jsp69.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp69.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp69.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp69);
        jsp69.setBounds(380, 255, 50, 25);

        jsp70.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp70.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp70.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp70);
        jsp70.setBounds(380, 285, 50, 25);

        jsp71.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp71.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp71.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp71);
        jsp71.setBounds(380, 315, 50, 25);

        jsp72.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp72.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp72.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp72);
        jsp72.setBounds(380, 345, 50, 25);

        jsp73.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp73.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp73.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp73);
        jsp73.setBounds(380, 375, 50, 25);

        jsp74.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp74.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp74.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp74);
        jsp74.setBounds(380, 445, 50, 25);

        jsp75.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp75.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp75.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp75);
        jsp75.setBounds(380, 475, 50, 25);

        jsp76.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp76.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp76.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp76);
        jsp76.setBounds(380, 505, 50, 25);

        jsp77.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp77.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp77.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp77);
        jsp77.setBounds(380, 535, 50, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icc.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 40, 95, 160);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rr.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 260, 98, 135);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wa.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(188, 447, 110, 110);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBackground.jpg"))); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background);
        Background.setBounds(0, 0, 450, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        addItems();
        new Menu().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose(); 
    }
    void addItems()
    {
        int bk=(Integer)jsp63.getValue();
        int bl=(Integer)jsp64.getValue();
        int bm=(Integer)jsp65.getValue();
        int bn=(Integer)jsp66.getValue();
        int bo=(Integer)jsp67.getValue();
        int bp=(Integer)jsp68.getValue();
        int bq=(Integer)jsp69.getValue();
        int br=(Integer)jsp70.getValue();
        int bs=(Integer)jsp71.getValue();
        int bt=(Integer)jsp72.getValue();
        int bu=(Integer)jsp73.getValue();
        int bv=(Integer)jsp74.getValue();
        int bw=(Integer)jsp75.getValue();
        int bx=(Integer)jsp76.getValue();
        int by=(Integer)jsp77.getValue();
        if (bk!=0)
        {
            MyClass.orderr.add(new Products("VANILLA SOFT SERVE ",15,bk));
        }
        if (bl!=0)
        {
            MyClass.orderr.add(new Products("BUTTER. SOFT SERVE  ",20,bl));
        }
        if (bm!=0)
        {
            MyClass.orderr.add(new Products("CHOC DIPSOFT SERVE",25,bm));
        }
        if (bn!=0)
        {
            MyClass.orderr.add(new Products("STRAWBERRY SCOOP ",40,bn));
        }
        if (bo!=0)
        {
            MyClass.orderr.add(new Products("RAINBOW SUNDAE    ",55,bo));
        }
        if (bp!=0)
        {
            MyClass.orderr.add(new Products("KIT-KAT MCFLURRY    ",65,bp));
        }
        if (bq!=0)
        {
            MyClass.orderr.add(new Products("DRY MUFFIN  CAKE    ",30,bq));
        }
        if (br!=0)
        {
            MyClass.orderr.add(new Products("CHOCO LAVA  CAKE   ",45,br));
        }
        if (bs!=0)
        {
            MyClass.orderr.add(new Products("CHOCOLATEBROWNIE",65,bs));
        }
        if (bt!=0)
        {
            MyClass.orderr.add(new Products("RED VELVET PASTRY   ",70,bt));
        }
        if (bu!=0)
        {
            MyClass.orderr.add(new Products("FRUIT CHEESE PASTRY",80,bu));
        }
        if (bv!=0)
        {
            MyClass.orderr.add(new Products("GULAB-JAMUN(1pc.)  ",15,bv));
        }
        if (bw!=0)
        {
            MyClass.orderr.add(new Products("MOONG DAL HALWA",40,bw));
        }
        if (bx!=0)
        {
            MyClass.orderr.add(new Products("GAJAR HALWA            ",45,bx));
        }
        if (by!=0)
        {
            MyClass.orderr.add(new Products("RASMALAAI (1pc.)       ",20,by));
        }// TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void proceedtopayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedtopayActionPerformed
    addItems();
    new Bill().setVisible(true);
    dispose();// TODO add your handling code here:
    }//GEN-LAST:event_proceedtopayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deserts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deserts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private java.awt.Label Coolers;
    private javax.swing.JLabel Frenchfries;
    private javax.swing.JLabel Frenchfries1;
    private javax.swing.JLabel Frenchfries10;
    private javax.swing.JLabel Frenchfries11;
    private javax.swing.JLabel Frenchfries12;
    private javax.swing.JLabel Frenchfries13;
    private javax.swing.JLabel Frenchfries14;
    private javax.swing.JLabel Frenchfries15;
    private javax.swing.JLabel Frenchfries2;
    private javax.swing.JLabel Frenchfries3;
    private javax.swing.JLabel Frenchfries4;
    private javax.swing.JLabel Frenchfries5;
    private javax.swing.JLabel Frenchfries6;
    private javax.swing.JLabel Frenchfries7;
    private javax.swing.JLabel Frenchfries8;
    private javax.swing.JLabel Frenchfries9;
    private java.awt.Label Milkshake;
    private java.awt.Label Milkshake1;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jsp63;
    private javax.swing.JSpinner jsp64;
    private javax.swing.JSpinner jsp65;
    private javax.swing.JSpinner jsp66;
    private javax.swing.JSpinner jsp67;
    private javax.swing.JSpinner jsp68;
    private javax.swing.JSpinner jsp69;
    private javax.swing.JSpinner jsp70;
    private javax.swing.JSpinner jsp71;
    private javax.swing.JSpinner jsp72;
    private javax.swing.JSpinner jsp73;
    private javax.swing.JSpinner jsp74;
    private javax.swing.JSpinner jsp75;
    private javax.swing.JSpinner jsp76;
    private javax.swing.JSpinner jsp77;
    private javax.swing.JButton menu;
    private javax.swing.JButton proceedtopay;
    // End of variables declaration//GEN-END:variables
}
