/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
         setSize(680,418);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pizza = new javax.swing.JButton();
        burger = new javax.swing.JButton();
        meals = new javax.swing.JButton();
        desert = new javax.swing.JButton();
        shakes = new javax.swing.JButton();
        aboutus = new javax.swing.JButton();
        proceedtopay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MENU");
        setLocation(new java.awt.Point(300, 100));
        setResizable(false);
        getContentPane().setLayout(null);

        pizza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pizza.setText("PIZZAS");
        pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaActionPerformed(evt);
            }
        });
        getContentPane().add(pizza);
        pizza.setBounds(55, 110, 165, 30);

        burger.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        burger.setText("BURGERS & ROLLS");
        burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerActionPerformed(evt);
            }
        });
        getContentPane().add(burger);
        burger.setBounds(55, 190, 165, 30);

        meals.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        meals.setText("FRIES & MEALS");
        meals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealsActionPerformed(evt);
            }
        });
        getContentPane().add(meals);
        meals.setBounds(455, 110, 165, 30);

        desert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        desert.setText("DESERTS");
        desert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desertActionPerformed(evt);
            }
        });
        getContentPane().add(desert);
        desert.setBounds(455, 190, 165, 30);

        shakes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        shakes.setText(" BEVERAGES");
        shakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shakesActionPerformed(evt);
            }
        });
        getContentPane().add(shakes);
        shakes.setBounds(55, 270, 165, 30);

        aboutus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aboutus.setText("ABOUT US");
        aboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutusActionPerformed(evt);
            }
        });
        getContentPane().add(aboutus);
        aboutus.setBounds(455, 270, 165, 30);

        proceedtopay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        proceedtopay.setForeground(new java.awt.Color(255, 51, 51));
        proceedtopay.setText("PROCEED TO PAY");
        proceedtopay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedtopayActionPerformed(evt);
            }
        });
        getContentPane().add(proceedtopay);
        proceedtopay.setBounds(485, 340, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/food.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 670, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaActionPerformed
     new Pizza().setVisible(true);
     dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_pizzaActionPerformed

    private void burgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerActionPerformed
      new Burger().setVisible(true);  
      dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_burgerActionPerformed

    private void shakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shakesActionPerformed
    new Beverages().setVisible(true); 
    dispose();// TODO add your handling code here:
    }//GEN-LAST:event_shakesActionPerformed

    private void mealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealsActionPerformed
    new Meals().setVisible(true);
    dispose();// TODO add your handling code here:
    }//GEN-LAST:event_mealsActionPerformed

    private void desertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desertActionPerformed
    new Deserts().setVisible(true);
    dispose();// TODO add your handling code here:
    }//GEN-LAST:event_desertActionPerformed

    private void aboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutusActionPerformed
    new About().setVisible(true);
    dispose();// TODO add your handling code here:
    }//GEN-LAST:event_aboutusActionPerformed

    private void proceedtopayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedtopayActionPerformed
    new Bill().setVisible(true); 
    dispose();// TODO add your handling code here:
    }//GEN-LAST:event_proceedtopayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutus;
    private javax.swing.JButton burger;
    private javax.swing.JButton desert;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton meals;
    private javax.swing.JButton pizza;
    private javax.swing.JButton proceedtopay;
    private javax.swing.JButton shakes;
    // End of variables declaration//GEN-END:variables
}
