/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class Pizza extends javax.swing.JFrame {

    /**
     * Creates new form Pizza
     */
    public Pizza() {
        initComponents();
        setSize(684,520);
        //Add Loop
        for(Products pp:MyClass.orderr)
        {
            if("CORN PIZZA              ".equals(pp.name))
            {
                this.jsp1.setValue(pp.qty);
            }
            if("ONION PIZZA            ".equals(pp.name))
            {
                this.jsp2.setValue(pp.qty);
            }
            if("ONION&CAP PIZZA   ".equals(pp.name))
            {
                this.jsp3.setValue(pp.qty);
            }
            if("ONION&PAN PIZZA   ".equals(pp.name))
            {
                this.jsp4.setValue(pp.qty);
            }
            if("TOM&CORN PIZZA    ".equals(pp.name))
            {
                this.jsp5.setValue(pp.qty);
            }
            if("ORIGANO                   ".equals(pp.name))
            {
                this.jsp6.setValue(pp.qty);
            }
            if("CILLI FLAKES               ".equals(pp.name))
            {
                this.jsp7.setValue(pp.qty);
            }
            if("TANDOORI MAYO DIP".equals(pp.name))
            {
                this.jsp8.setValue(pp.qty);
            }
            if("PEPSI(400 ml)              ".equals(pp.name))
            {
                this.jsp18.setValue(pp.qty);
            }
            if("CLASSIC MARGHERITA".equals(pp.name))
            {
                this.jsp9.setValue(pp.qty);
            }
            if("FARM FRESH               ".equals(pp.name))
            {
                this.jsp10.setValue(pp.qty);
            }
            if("TANDOORI PANEER    ".equals(pp.name))
            {
                this.jsp11.setValue(pp.qty);
            }
            if("TRIPLE TANGO TWIST ".equals(pp.name))
            {
                this.jsp12.setValue(pp.qty);
            }
            if("VEG. MEXICANA         ".equals(pp.name))
            {
                this.jsp13.setValue(pp.qty);
            }
            if("VEG. GOURMET          ".equals(pp.name))
            {
                this.jsp14.setValue(pp.qty);
            }
            if("PANEER MAKHNI        ".equals(pp.name))
            {
                this.jsp15.setValue(pp.qty);
            }
            if("MIX VEG. PIZZA          ".equals(pp.name))
            {
                this.jsp16.setValue(pp.qty);
            }
            if("VEG. PARADISE           ".equals(pp.name))
            {
                this.jsp17.setValue(pp.qty);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Pizzaphoto = new javax.swing.JLabel();
        Serves = new javax.swing.JLabel();
        Cornpizza = new javax.swing.JLabel();
        Onionpizza = new javax.swing.JLabel();
        Small = new javax.swing.JLabel();
        Onioncap = new javax.swing.JLabel();
        Onionpaner = new javax.swing.JLabel();
        Tomcorn = new javax.swing.JLabel();
        Pizzaphoto2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Origano = new javax.swing.JLabel();
        ChilliFlakes = new javax.swing.JLabel();
        Mayodip = new javax.swing.JLabel();
        Tandoorimayo = new javax.swing.JLabel();
        Pizzaphoto1 = new javax.swing.JLabel();
        Regular = new javax.swing.JLabel();
        Medium = new javax.swing.JLabel();
        Serves1 = new javax.swing.JLabel();
        Serves2 = new javax.swing.JLabel();
        Large = new javax.swing.JLabel();
        Serves4 = new javax.swing.JLabel();
        Classic = new javax.swing.JLabel();
        farmfresh = new javax.swing.JLabel();
        Des = new javax.swing.JLabel();
        Des1 = new javax.swing.JLabel();
        Tandoori = new javax.swing.JLabel();
        Des2 = new javax.swing.JLabel();
        Triplett = new javax.swing.JLabel();
        Des3 = new javax.swing.JLabel();
        vegmec = new javax.swing.JLabel();
        Triplett1 = new javax.swing.JLabel();
        Des4 = new javax.swing.JLabel();
        Triplett2 = new javax.swing.JLabel();
        Des5 = new javax.swing.JLabel();
        Triplett3 = new javax.swing.JLabel();
        Des6 = new javax.swing.JLabel();
        Triplett4 = new javax.swing.JLabel();
        Des7 = new javax.swing.JLabel();
        Des8 = new javax.swing.JLabel();
        Singletopping = new java.awt.Label();
        Doubletopping = new java.awt.Label();
        Choiceofbase = new java.awt.Label();
        VegPizzas = new java.awt.Label();
        jsp1 = new javax.swing.JSpinner();
        jsp2 = new javax.swing.JSpinner();
        jsp3 = new javax.swing.JSpinner();
        jsp4 = new javax.swing.JSpinner();
        jsp5 = new javax.swing.JSpinner();
        jsp6 = new javax.swing.JSpinner();
        jsp7 = new javax.swing.JSpinner();
        jsp8 = new javax.swing.JSpinner();
        jsp9 = new javax.swing.JSpinner();
        jsp10 = new javax.swing.JSpinner();
        jsp11 = new javax.swing.JSpinner();
        jsp12 = new javax.swing.JSpinner();
        jsp13 = new javax.swing.JSpinner();
        jsp14 = new javax.swing.JSpinner();
        jsp15 = new javax.swing.JSpinner();
        jsp16 = new javax.swing.JSpinner();
        jsp17 = new javax.swing.JSpinner();
        jsp18 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        proceedtopay = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PIZZAS");
        setLocation(new java.awt.Point(300, 60));
        setResizable(false);
        getContentPane().setLayout(null);

        Pizzaphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dd.jpg"))); // NOI18N
        getContentPane().add(Pizzaphoto);
        Pizzaphoto.setBounds(140, 190, 80, 80);

        Serves.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Serves.setText("Serves- 1 ");
        getContentPane().add(Serves);
        Serves.setBounds(260, 45, 60, 16);

        Cornpizza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cornpizza.setText("Corn Pizza");
        getContentPane().add(Cornpizza);
        Cornpizza.setBounds(5, 65, 90, 25);

        Onionpizza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Onionpizza.setText("Onion Pizza");
        getContentPane().add(Onionpizza);
        Onionpizza.setBounds(5, 95, 90, 25);

        Small.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Small.setText("Small (7 inch)");
        getContentPane().add(Small);
        Small.setBounds(240, 30, 80, 16);

        Onioncap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Onioncap.setText("Onion & Capsicum");
        getContentPane().add(Onioncap);
        Onioncap.setBounds(5, 185, 121, 25);

        Onionpaner.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Onionpaner.setText("Onion & Paneer");
        getContentPane().add(Onionpaner);
        Onionpaner.setBounds(5, 215, 104, 25);

        Tomcorn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tomcorn.setText("Tomato & Corn");
        getContentPane().add(Tomcorn);
        Tomcorn.setBounds(5, 245, 101, 25);

        Pizzaphoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ss.jpg"))); // NOI18N
        Pizzaphoto2.setText("jLabel7");
        getContentPane().add(Pizzaphoto2);
        Pizzaphoto2.setBounds(140, 65, 80, 60);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("75/-");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 65, 35, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("75/-");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(230, 95, 35, 25);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("105/-");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(230, 185, 35, 25);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("110/-");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(230, 215, 35, 25);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("110/-");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(230, 245, 35, 25);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("25/-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(230, 330, 35, 25);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("30/-");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(230, 360, 35, 25);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("35/-");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(230, 390, 35, 25);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("195/-");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(560, 70, 35, 25);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("260/-");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(560, 230, 35, 25);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("325/-");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(560, 350, 35, 25);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("40/-");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(230, 420, 35, 25);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("195/-");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(560, 110, 35, 25);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 51, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("245/-");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(560, 150, 35, 25);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("245/-");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(560, 190, 35, 25);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 51, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("260/-");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(560, 270, 35, 25);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("295/-");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(560, 310, 35, 25);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("325/-");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(560, 390, 35, 25);

        Origano.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Origano.setText("Origano");
        getContentPane().add(Origano);
        Origano.setBounds(5, 330, 90, 25);

        ChilliFlakes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChilliFlakes.setText("Chilli Flakes");
        getContentPane().add(ChilliFlakes);
        ChilliFlakes.setBounds(5, 360, 90, 25);

        Mayodip.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mayodip.setText("Tandoori Mayo Dip");
        getContentPane().add(Mayodip);
        Mayodip.setBounds(5, 390, 130, 25);

        Tandoorimayo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tandoorimayo.setText("Pepsi(400 ml.)");
        getContentPane().add(Tandoorimayo);
        Tandoorimayo.setBounds(5, 420, 130, 25);

        Pizzaphoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aa.jpg"))); // NOI18N
        getContentPane().add(Pizzaphoto1);
        Pizzaphoto1.setBounds(140, 335, 80, 90);

        Regular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Regular.setText("Regular");
        getContentPane().add(Regular);
        Regular.setBounds(383, 30, 50, 16);

        Medium.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Medium.setText("Medium");
        getContentPane().add(Medium);
        Medium.setBounds(495, 30, 50, 16);

        Serves1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Serves1.setText("Serves- 1 ");
        getContentPane().add(Serves1);
        Serves1.setBounds(374, 45, 60, 16);

        Serves2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Serves2.setText("Serves- 2 ");
        getContentPane().add(Serves2);
        Serves2.setBounds(488, 45, 60, 16);

        Large.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Large.setText("Large");
        getContentPane().add(Large);
        Large.setBounds(598, 30, 50, 16);

        Serves4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Serves4.setText("Serves- 4 ");
        getContentPane().add(Serves4);
        Serves4.setBounds(591, 45, 60, 16);

        Classic.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Classic.setText("Classic Margherita");
        getContentPane().add(Classic);
        Classic.setBounds(350, 65, 124, 25);

        farmfresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        farmfresh.setText("Farm Fresh");
        getContentPane().add(farmfresh);
        farmfresh.setBounds(350, 100, 90, 25);

        Des.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des.setText("(Super Cheesy Topping)");
        Des.setAlignmentY(0.0F);
        getContentPane().add(Des);
        Des.setBounds(350, 85, 124, 12);

        Des1.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des1.setText("(Onion, Capsicum, Tomato, Mushroom)");
        Des1.setAlignmentY(0.0F);
        getContentPane().add(Des1);
        Des1.setBounds(350, 120, 170, 12);

        Tandoori.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tandoori.setText("Tandoori Paneer");
        getContentPane().add(Tandoori);
        Tandoori.setBounds(350, 140, 124, 25);

        Des2.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des2.setText("(Onion, Jalapeno, Tomato, Paneer, Corn)");
        Des2.setAlignmentY(0.0F);
        getContentPane().add(Des2);
        Des2.setBounds(350, 160, 180, 12);

        Triplett.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Triplett.setText("Triple Tango Twist");
        getContentPane().add(Triplett);
        Triplett.setBounds(350, 180, 130, 25);

        Des3.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des3.setText("(Babycorn, Pineapple, Paneer, Spicy Sauce)");
        Des3.setAlignmentY(0.0F);
        getContentPane().add(Des3);
        Des3.setBounds(350, 200, 190, 12);

        vegmec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vegmec.setText("Veg. Mexicana");
        getContentPane().add(vegmec);
        vegmec.setBounds(350, 220, 130, 25);

        Triplett1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Triplett1.setText("Veg. Gourmet");
        getContentPane().add(Triplett1);
        Triplett1.setBounds(350, 260, 130, 25);

        Des4.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des4.setText("(Mushroom, Corn, Red Peprika, Tomato)");
        Des4.setAlignmentY(0.0F);
        getContentPane().add(Des4);
        Des4.setBounds(350, 240, 210, 12);

        Triplett2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Triplett2.setText("Paneer Makhni");
        getContentPane().add(Triplett2);
        Triplett2.setBounds(350, 300, 130, 25);

        Des5.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des5.setText("(Jalapeno, Black Olives, Corn, Extra Cheese)");
        Des5.setAlignmentY(0.0F);
        getContentPane().add(Des5);
        Des5.setBounds(350, 280, 200, 12);

        Triplett3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Triplett3.setText("Mix Veg. Pizza");
        getContentPane().add(Triplett3);
        Triplett3.setBounds(350, 340, 130, 25);

        Des6.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des6.setText("(Paneer, Red Peprika, Onion, Corn, Spicy Sauce)");
        Des6.setAlignmentY(0.0F);
        getContentPane().add(Des6);
        Des6.setBounds(350, 320, 214, 12);

        Triplett4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Triplett4.setText("Veg. Paradise");
        getContentPane().add(Triplett4);
        Triplett4.setBounds(350, 380, 130, 25);

        Des7.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des7.setText("(Onion, Capsicum, Tomato, Mushroom, Cheese)");
        Des7.setAlignmentY(0.0F);
        getContentPane().add(Des7);
        Des7.setBounds(350, 360, 214, 12);

        Des8.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        Des8.setText("(Mushroom, Olives, Jalapeno, Baby Corn, Cheese )");
        Des8.setAlignmentY(0.0F);
        getContentPane().add(Des8);
        Des8.setBounds(350, 400, 220, 12);

        Singletopping.setAlignment(java.awt.Label.CENTER);
        Singletopping.setBackground(new java.awt.Color(102, 102, 102));
        Singletopping.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Singletopping.setForeground(new java.awt.Color(255, 255, 255));
        Singletopping.setText("SINGLE TOPPING PIZZA");
        getContentPane().add(Singletopping);
        Singletopping.setBounds(0, 0, 320, 30);

        Doubletopping.setAlignment(java.awt.Label.CENTER);
        Doubletopping.setBackground(new java.awt.Color(102, 102, 102));
        Doubletopping.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Doubletopping.setForeground(new java.awt.Color(255, 255, 255));
        Doubletopping.setText("DOUBLE TOPPING PIZZA");
        getContentPane().add(Doubletopping);
        Doubletopping.setBounds(0, 150, 320, 30);

        Choiceofbase.setAlignment(java.awt.Label.CENTER);
        Choiceofbase.setBackground(new java.awt.Color(102, 102, 102));
        Choiceofbase.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Choiceofbase.setForeground(new java.awt.Color(255, 255, 255));
        Choiceofbase.setText("DIPS & DRINKS");
        getContentPane().add(Choiceofbase);
        Choiceofbase.setBounds(0, 295, 320, 30);

        VegPizzas.setAlignment(java.awt.Label.CENTER);
        VegPizzas.setBackground(new java.awt.Color(102, 102, 102));
        VegPizzas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VegPizzas.setForeground(new java.awt.Color(255, 255, 255));
        VegPizzas.setText("VEG PIZZAS");
        getContentPane().add(VegPizzas);
        VegPizzas.setBounds(350, 0, 320, 30);

        jsp1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsp1.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jsp1);
        jsp1.setBounds(265, 65, 50, 25);

        jsp2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp2);
        jsp2.setBounds(265, 95, 50, 25);

        jsp3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp3);
        jsp3.setBounds(265, 185, 50, 25);

        jsp4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp4);
        jsp4.setBounds(265, 215, 50, 25);

        jsp5.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp5);
        jsp5.setBounds(265, 245, 50, 25);

        jsp6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp6);
        jsp6.setBounds(265, 330, 50, 25);

        jsp7.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp7);
        jsp7.setBounds(265, 360, 50, 25);

        jsp8.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp8);
        jsp8.setBounds(265, 390, 50, 25);

        jsp9.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp9);
        jsp9.setBounds(600, 70, 60, 25);

        jsp10.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp10);
        jsp10.setBounds(600, 110, 60, 25);

        jsp11.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp11);
        jsp11.setBounds(600, 150, 60, 25);

        jsp12.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp12);
        jsp12.setBounds(600, 190, 60, 25);

        jsp13.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp13);
        jsp13.setBounds(600, 230, 60, 25);

        jsp14.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp14);
        jsp14.setBounds(600, 270, 60, 25);

        jsp15.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp15);
        jsp15.setBounds(600, 310, 60, 25);

        jsp16.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp16);
        jsp16.setBounds(600, 350, 60, 25);

        jsp17.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp17);
        jsp17.setBounds(600, 390, 60, 25);

        jsp18.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jsp18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jsp18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jsp18);
        jsp18.setBounds(265, 420, 50, 25);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(460, 30, 10, 30);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 130, 320, 10);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 275, 320, 10);

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(0, 445, 684, 3);

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(350, 60, 320, 10);

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(570, 30, 10, 30);

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(333, 0, 10, 445);

        proceedtopay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        proceedtopay.setForeground(new java.awt.Color(255, 51, 51));
        proceedtopay.setText("PROCEED TO BILL");
        proceedtopay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedtopayActionPerformed(evt);
            }
        });
        getContentPane().add(proceedtopay);
        proceedtopay.setBounds(284, 450, 150, 30);

        menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu.setText("MENU");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu);
        menu.setBounds(441, 450, 120, 30);

        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(567, 450, 100, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzaBackground.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 670, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        addItems();
        new Menu().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed
    void addItems()
    {
        int a=(Integer)jsp1.getValue();
        int b=(Integer)jsp2.getValue();
        int c=(Integer)jsp3.getValue();
        int d=(Integer)jsp4.getValue();
        int e=(Integer)jsp5.getValue();
        int f=(Integer)jsp6.getValue();
        int g=(Integer)jsp7.getValue();
        int h=(Integer)jsp8.getValue();
        int i=(Integer)jsp18.getValue();
        int j=(Integer)jsp9.getValue();
        int k=(Integer)jsp10.getValue();
        int l=(Integer)jsp11.getValue();
        int m=(Integer)jsp12.getValue();
        int n=(Integer)jsp13.getValue();
        int o=(Integer)jsp14.getValue();
        int p=(Integer)jsp15.getValue();
        int q=(Integer)jsp16.getValue();
        int r=(Integer)jsp17.getValue();
        if (a!=0)
        {
            MyClass.orderr.add(new Products("CORN PIZZA              ",75,a));
            
        }
        if (b!=0)
        {
            MyClass.orderr.add(new Products("ONION PIZZA            ",75,b));         
        }
        if (c!=0)
        {
            MyClass.orderr.add(new Products("ONION&CAP PIZZA   ",105,c));
            
        }
        if (d!=0)
        {
            MyClass.orderr.add(new Products("ONION&PAN PIZZA   ",110,d));
            
        }
        if (e!=0)
        {
            MyClass.orderr.add(new Products("TOM&CORN PIZZA    ",110,e));
            
        }
        if (f!=0)
        {
            MyClass.orderr.add(new Products("ORIGANO                   ",25,f));
            
        }
        if (g!=0)
        {
            MyClass.orderr.add(new Products("CILLI FLAKES               ",30,g));
            
        }
        if (h!=0)
        {
            MyClass.orderr.add(new Products("TANDOORI MAYO DIP",35,h));
            
        }
        if (i!=0)
        {
            MyClass.orderr.add(new Products("PEPSI(400 ml)              ",40,i));
            
        }
        if (j!=0)
        {
            MyClass.orderr.add(new Products("CLASSIC MARGHERITA",195,j));
            
        }
        if (k!=0)
        {
            MyClass.orderr.add(new Products("FARM FRESH               ",195,k));
            
        }
        if (l!=0)
        {
            MyClass.orderr.add(new Products("TANDOORI PANEER    ",245,l));
            
        }
        if (m!=0)
        {
            MyClass.orderr.add(new Products("TRIPLE TANGO TWIST ",245,m));
            
        }
        if (n!=0)
        {
            MyClass.orderr.add(new Products("VEG. MEXICANA         ",260,n));
            
        }
        if (o!=0)
        {
            MyClass.orderr.add(new Products("VEG. GOURMET          ",260,o));
            
        }
        if (p!=0)
        {
            MyClass.orderr.add(new Products("PANEER MAKHNI        ",295,p));
            
        }
        if (q!=0)
        {
            MyClass.orderr.add(new Products("MIX VEG. PIZZA          ",325,q));
            
        }
        if (r!=0)
        {
            MyClass.orderr.add(new Products("VEG. PARADISE           ",325,r));
            
        }
    }
    private void proceedtopayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedtopayActionPerformed
        addItems();
        new Bill().setVisible(true);
        dispose();/// TODO add your handling code here:
    }//GEN-LAST:event_proceedtopayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>8

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel ChilliFlakes;
    private java.awt.Label Choiceofbase;
    private javax.swing.JLabel Classic;
    private javax.swing.JLabel Cornpizza;
    private javax.swing.JLabel Des;
    private javax.swing.JLabel Des1;
    private javax.swing.JLabel Des2;
    private javax.swing.JLabel Des3;
    private javax.swing.JLabel Des4;
    private javax.swing.JLabel Des5;
    private javax.swing.JLabel Des6;
    private javax.swing.JLabel Des7;
    private javax.swing.JLabel Des8;
    private java.awt.Label Doubletopping;
    private javax.swing.JLabel Large;
    private javax.swing.JLabel Mayodip;
    private javax.swing.JLabel Medium;
    private javax.swing.JLabel Onioncap;
    private javax.swing.JLabel Onionpaner;
    private javax.swing.JLabel Onionpizza;
    private javax.swing.JLabel Origano;
    private javax.swing.JLabel Pizzaphoto;
    private javax.swing.JLabel Pizzaphoto1;
    private javax.swing.JLabel Pizzaphoto2;
    private javax.swing.JLabel Regular;
    private javax.swing.JLabel Serves;
    private javax.swing.JLabel Serves1;
    private javax.swing.JLabel Serves2;
    private javax.swing.JLabel Serves4;
    private java.awt.Label Singletopping;
    private javax.swing.JLabel Small;
    private javax.swing.JLabel Tandoori;
    private javax.swing.JLabel Tandoorimayo;
    private javax.swing.JLabel Tomcorn;
    private javax.swing.JLabel Triplett;
    private javax.swing.JLabel Triplett1;
    private javax.swing.JLabel Triplett2;
    private javax.swing.JLabel Triplett3;
    private javax.swing.JLabel Triplett4;
    private java.awt.Label VegPizzas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exit;
    private javax.swing.JLabel farmfresh;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSpinner jsp1;
    private javax.swing.JSpinner jsp10;
    private javax.swing.JSpinner jsp11;
    private javax.swing.JSpinner jsp12;
    private javax.swing.JSpinner jsp13;
    private javax.swing.JSpinner jsp14;
    private javax.swing.JSpinner jsp15;
    private javax.swing.JSpinner jsp16;
    private javax.swing.JSpinner jsp17;
    private javax.swing.JSpinner jsp18;
    private javax.swing.JSpinner jsp2;
    private javax.swing.JSpinner jsp3;
    private javax.swing.JSpinner jsp4;
    private javax.swing.JSpinner jsp5;
    private javax.swing.JSpinner jsp6;
    private javax.swing.JSpinner jsp7;
    private javax.swing.JSpinner jsp8;
    private javax.swing.JSpinner jsp9;
    private javax.swing.JButton menu;
    private javax.swing.JButton proceedtopay;
    private javax.swing.JLabel vegmec;
    // End of variables declaration//GEN-END:variables
}
