/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anshv
 */
public class QR extends javax.swing.JFrame {

    /**
     * Creates new form QR
     */
    public QR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Checkup = new javax.swing.JButton();
        Checkup1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PAYMENT");
        setLocation(new java.awt.Point(440, 120));
        setMaximumSize(new java.awt.Dimension(500, 460));
        setMinimumSize(new java.awt.Dimension(500, 460));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qr.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 20, 300, 260);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Scanning this QR Code the payment can be done through \nUPI or Net Banking and if the payment is in cash, you can\ndirectly pay to the staff at the time of receiving your order.\n                                           Thankyou!");
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 290, 370, 90);

        Checkup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Checkup.setText("PAY IN CASH");
        Checkup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckupActionPerformed(evt);
            }
        });
        getContentPane().add(Checkup);
        Checkup.setBounds(40, 380, 200, 30);

        Checkup1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Checkup1.setForeground(new java.awt.Color(255, 51, 51));
        Checkup1.setText("PAID");
        Checkup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Checkup1ActionPerformed(evt);
            }
        });
        getContentPane().add(Checkup1);
        Checkup1.setBounds(250, 380, 200, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whiteback.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckupActionPerformed
        new Submit().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CheckupActionPerformed

    private void Checkup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Checkup1ActionPerformed
        new Submit().setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_Checkup1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Checkup;
    private javax.swing.JButton Checkup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
