/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author anshv
 */
public class Register extends javax.swing.JFrame {
    Connection con;
    PreparedStatement ptst;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/db1","root","");
        }catch(Exception ee)
        {
            JOptionPane.showMessageDialog(this,"Start the Database Server");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phone = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        name1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTER FOR NEW CUSTOMER");
        setBounds(new java.awt.Rectangle(390, 90, 400, 400));
        setLocation(new java.awt.Point(400, 100));
        setMinimumSize(new java.awt.Dimension(380, 440));
        getContentPane().setLayout(null);

        phone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        phone.setText("Phone No  :");
        getContentPane().add(phone);
        phone.setBounds(60, 215, 80, 30);

        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name.setText("First Name:");
        getContentPane().add(name);
        name.setBounds(60, 145, 80, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 145, 180, 30);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 215, 180, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Pincode     :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 250, 80, 30);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(150, 250, 180, 30);

        Submit.setBackground(new java.awt.Color(51, 153, 255));
        Submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(45, 320, 130, 30);

        Reset.setBackground(new java.awt.Color(51, 153, 255));
        Reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Reset.setForeground(new java.awt.Color(255, 51, 51));
        Reset.setText("RESET");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset);
        Reset.setBounds(190, 320, 130, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(150, 180, 180, 30);

        name1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name1.setText("Last Name :");
        getContentPane().add(name1);
        name1.setBounds(60, 180, 80, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USER SIGNUP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 25, 380, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nWxtjQH.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-130, -60, 610, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
    String rr=jTextField1.getText();
    String zz=jTextField2.getText();
    String xx=jTextField3.getText();
    String yy=jTextField4.getText();
    String vv=rr+" "+yy;
        try{
        String sql="insert into credentials values(?,?,?)";
        ptst=con.prepareStatement(sql);
        ptst.setString(1,jTextField2.getText());
        ptst.setString(2,vv);
        ptst.setString(3,jTextField3.getText());
        if(zz.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter number.");
        }
        else if(zz.length()<10)
        {
            JOptionPane.showMessageDialog(this, "Please enter valid number.");
        }
        else if(xx.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter your area pincode.");
        }
        else if(xx.length()<6)
        {
            JOptionPane.showMessageDialog(this, "Please enter valid pincode.");
        }
        else
        {
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Credentials Saved, Please Login!");
            new welcome().setVisible(true);   
            System.exit(0);// TODO add your handling code here:
        }
    }catch(Exception ee){
        JOptionPane.showMessageDialog(this,"DB Error");  
    }
    }//GEN-LAST:event_SubmitActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");  
    jTextField4.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_ResetActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
    char c=evt.getKeyChar();
    String s=jTextField1.getText();
    if(c<65 || c>122 || s.length()>40)
    evt.consume();// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
    char c=evt.getKeyChar();
    String s=jTextField2.getText();
    if(c<48 || c>57 || s.length()>9)
    evt.consume();
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
    char d=evt.getKeyChar();
    String h=jTextField3.getText();
    if(d<48 || d>57 || h.length()>5)
    evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
    int a=evt.getKeyCode();
        if(a==10)
        {
    String rr=jTextField1.getText();
    String zz=jTextField2.getText();
    String xx=jTextField3.getText();
    String yy=jTextField4.getText();
    String vv=rr+" "+yy;
        try{
        String sql="insert into credentials values(?,?,?)";
        ptst=con.prepareStatement(sql);
        ptst.setString(1,jTextField2.getText());
        ptst.setString(2,vv);
        ptst.setString(3,jTextField3.getText());
        if(zz.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter number.");
        }
        else if(zz.length()<10)
        {
            JOptionPane.showMessageDialog(this, "Please enter valid number.");
        }
        else if(xx.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please enter your area pincode.");
        }
        else if(xx.length()<6)
        {
            JOptionPane.showMessageDialog(this, "Please enter valid pincode.");
        }
        else
        {
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Credentials Saved, Please Login!");
            new welcome().setVisible(true);   
            System.exit(0);// TODO add your handling code here:
        }
    }catch(Exception ee){
        JOptionPane.showMessageDialog(this,"DB Error");  
    }
    }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
    char c=evt.getKeyChar();
    String s=jTextField4.getText();
    if(c<65 || c>122 || s.length()>40)
    evt.consume();    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel phone;
    // End of variables declaration//GEN-END:variables
}
